### PR TITLE
Add `Keep visualizations` checkbox to training GUI

### PR DESCRIPTION
**Pull request by hajin-park**
### Description
This PR clarifies the use of the `Visualize Predictions During Training` checkbox by adding a new `Keep Prediction Visualization Images After Training` checkbox to the training config GUI. If training visualization images are enabled, the images are deleted after training by default unless the new checkbox is enabled (checked).

### Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?

- #1016

### Outside contributors checklist

- [x] Review the [guidelines for contributing](https://github.com/talmolab/sleap/blob/develop/docs/CONTRIBUTING.md) to this repository
- [x] Read and sign the [CLA](https://github.com/talmolab/sleap/blob/develop/sleap-cla.pdf) and add yourself to the [authors list](https://github.com/talmolab/sleap/blob/develop/AUTHORS)
- [x] Make sure you are making a pull request against the **develop** branch (not *main*). Also you should start *your branch* off *develop*
- [x] Add tests that prove your fix is effective or that your feature works
- [x] Add necessary documentation (if appropriate)

#### Thank you for contributing to SLEAP!
:heart:

## Summary by CodeRabbit

- **New Features**
  - Introduced `--keep_viz` argument to retain prediction visualization images after training.
  - Renamed `--save_viz` argument to `--view_viz`.
  - Added `--delete_viz` argument for deleting visualization images after training.

- **Tests**
  - Added test `test_keep_viz_cli` to check the functionality of the `--keep_viz` option.
  - Updated tests to check visualization paths and save directories.

### CODE REVIEW

**Comment by hajin-park** [comment]
@coderabbitai review

**Comment by gitttt-1234** [comment]
From subgroup:
- Keep it named `save_visualizations`
- Add checkbox to GUI labeled "Keep visualization images after training" with a default value of off (unchecked)

**Comment by hajin-park** [comment]
@coderabbitai review

**Review by roomrys — APPROVED** [review]
Ready to merge after tests pass (post updating branch)

**Pull request merged**
